### PR TITLE
3 large unsigned ints marked with u in the end, as they were being mista...

### PR DESCRIPTION
**Pull request by jjts**
...kingly taken by signed ints on my Ubuntu 32-bit setup. This should improve portability.

### CODE REVIEW

**Comment by skristiansson** [comment]
Thanks, but this is already a known issue and unfortunately the fix isn't this easy.
The file you have changed is auto-generated by CGEN, so manual changes to that
isn't a very good idea. To properly fix the problem, the change should be made in the CGEN
code that generates this enum.

**Comment by jjts** [comment]
Thanks, I should have read the header but I was not expecting that that
auto-generated files were part of the repo, although I don't doubt there's
a good reason for that.
Could you point me to the repo where the CGEN code is ?

2013/10/21 Stefan Kristiansson notifications@github.com

**Comment by skristiansson** [comment]
On Mon, Oct 21, 2013 at 12:32 PM, Jose T. de Sousa <notifications@github.com

> wrote:
> 
> Thanks, I should have read the header but I was not expecting that that
> auto-generated files were part of the repo, although I don't doubt there's
> a good reason for that.
> Could you point me to the repo where the CGEN code is ?
> 
> it's a part of the or1k-src repo
> https://github.com/openrisc/or1k-src/tree/or1k/cgen

And the target specific files that are used by cgen (in this case or1k) are
in
https://github.com/openrisc/or1k-src/tree/or1k/cpu

Stefan

**Comment by pgavin** [comment]
I'm almost positive that in order to change this the CGEN sources have to
be modified.

Is this actually breaking anything?  32-bit integers should be used for
handling these values anyways, so sign extension shouldn't ever happen.  I
regularly use 64-bit, and I've never come across a problem with this.  If
it's not breaking anything for us, it might be best to just notify the
upstream devs and let the change come to us that way.

-Pete

**Comment by jjts** [comment]
compilation aborts on 32-bit systems. I managed to continue by editing the
.h file. After that compilation finished.

Is the .h file generated by running CGEN during the compilation? Or is it
run previously? If the former, one minor change that could be done is to
remove auto generated files from the repo. Then fix the CGEN sources or
patch its output with a filter....

2013/10/21 Peter Gavin notifications@github.com

> I'm almost positive that in order to change this the CGEN sources have to
> be modified.
> 
> Is this actually breaking anything? 32-bit integers should be used for
> handling these values anyways, so sign extension shouldn't ever happen. I
> regularly use 64-bit, and I've never come across a problem with this. If
> it's not breaking anything for us, it might be best to just notify the
> upstream devs and let the change come to us that way.
> 
> -Pete
> 
> On Mon, Oct 21, 2013 at 6:45 AM, Stefan Kristiansson <

**Comment by pgavin** [comment]
On Mon, Oct 21, 2013 at 5:04 PM, Jose T. de Sousa
notifications@github.comwrote:

> compilation aborts on 32-bit systems. I managed to continue by editing the
> .h file. After that compilation finished.

Oh, ok.

> Is the .h file generated by running CGEN during the compilation? Or is it
> run previously? If the former, one minor change that could be done is to
> remove auto generated files from the repo. Then fix the CGEN sources or
> patch its output with a filter....
> 
> You have to run configure with the --enable-cgen-maint flag to make it
> rebuild those files.  They're kept in the repo because that's the way
> upstream does it.

If you want to fix this problem, I'd suggest sending an email/patch to the
CGEN mailing list (see here: http://www.sourceware.org/cgen/).  The changes
required to fix it might break other targets, and they will know best how
to handle it.

-Pete

**Comment by skristiansson** [comment]
On Tue, Oct 22, 2013 at 12:42 AM, Peter Gavin notifications@github.comwrote:

> On Mon, Oct 21, 2013 at 5:04 PM, Jose T. de Sousa
> notifications@github.comwrote:
> 
> > compilation aborts on 32-bit systems. I managed to continue by editing
> > the
> > .h file. After that compilation finished.
> 
> Yes, but you can workaround that by feeding --disable-werror to configure.
> That combined with that the correct solution involves fiddling with the
> generic internals of
> CGEN is the reason why it hasn't been fixed yet. But really, it should be
> fixed,
> so if you'd want to take a shoot at it, it'd be appreciated.
> 
> > Is the .h file generated by running CGEN during the compilation? Or is it
> > run previously? If the former, one minor change that could be done is to
> > remove auto generated files from the repo. Then fix the CGEN sources or
> > patch its output with a filter....
> > 
> > You have to run configure with the --enable-cgen-maint flag to make it
> > rebuild those files. They're kept in the repo because that's the way
> > upstream does it.
> 
> If you want to fix this problem, I'd suggest sending an email/patch to the
> CGEN mailing list (see here: http://www.sourceware.org/cgen/). The changes
> required to fix it might break other targets, and they will know best how
> to handle it.
> 
> I agree, any ad-hoc hacks specific to or1k isn't worth it, if we're going
> to fix it,
> it should be done properly.

Stefan

**Comment by jjts** [comment]
I tried to contact the CGEN mailing list and sent some files but no
response ..... I put this in the back burner because I am facing a more
urgent issue which I will communicate next.

Thanks for the help anyway.

2013/10/22 Stefan Kristiansson notifications@github.com

> On Tue, Oct 22, 2013 at 12:42 AM, Peter Gavin <notifications@github.com
> 
> > wrote:
> > 
> > On Mon, Oct 21, 2013 at 5:04 PM, Jose T. de Sousa

**Pull request closed without merging**
